Repository nhnacademy-be10-WannaB/wannab-order-payment-service, pull requests merged in 2025-07, with the labels that each got.

#90 feat : 리뷰작성가능여부 확인
  src/main/java/shop/wannab/order_payment_service/controller/OrderController.java
  src/main/java/shop/wannab/order_payment_service/repository/OrderBookRepository.java
  src/main/java/shop/wannab/order_payment_service/service/OrderService.java
Labels: Feature

#100 Feature/issue 98/when order failed
  src/main/java/shop/wannab/order_payment_service/client/CouponClient.java
  src/main/java/shop/wannab/order_payment_service/entity/Order.java
  src/main/java/shop/wannab/order_payment_service/entity/OrderStatus.java
  src/main/java/shop/wannab/order_payment_service/repository/OrderRepository.java
  src/main/java/shop/wannab/order_payment_service/scheduler/OrderStatusScheduler.java
  src/main/java/shop/wannab/order_payment_service/service/OrderService.java
  src/main/java/shop/wannab/order_payment_service/service/PaymentService.java
Labels: Feature, Fix

#116 issue-111/feat : 임시포장지관리 crud
  src/main/java/shop/wannab/order_payment_service/controller/PavingController.java
  src/main/java/shop/wannab/order_payment_service/entity/Paving.java
  src/main/java/shop/wannab/order_payment_service/entity/dto/PavingRequest.java
  src/main/java/shop/wannab/order_payment_service/entity/dto/PavingResponse.java
  src/main/java/shop/wannab/order_payment_service/repository/PavingRepository.java
  src/main/java/shop/wannab/order_payment_service/service/PavingService.java
Labels: Feature

#137 결제 오류 수정 및 Key, prefix 프로퍼티로 수정
  src/main/java/shop/wannab/order_payment_service/properties/TossPaymentsProperties.java
  src/main/java/shop/wannab/order_payment_service/service/PaymentService.java
  src/main/resources/application-ci.yml
Labels: Feature

#140 debug 로그 level로 수정
  src/main/resources/logback-spring.xml
Labels: Refactor
